pub const FILES_TO_DOWNLOAD: [[&str; 2]; 17] = [
    ["SyntaxApp.zip", "./"],
    ["NPSyntaxProxy.zip", "./"],
    ["SyntaxProxy.zip", "./"],
    ["Libraries.zip", "./"],
    ["redist.zip", "./"],
    ["content-textures.zip", "./content/textures"],
    ["content-textures2.zip", "./content/textures"],
    ["content-textures3.zip", "./PlatformContent/pc/textures"],
    ["content-terrain.zip", "./PlatformContent/pc/terrain"],
    ["content-fonts.zip", "./content/fonts"],
    ["content-sounds.zip", "./content/sounds"],
    ["content-scripts.zip", "./content/scripts"],
    ["content-sky.zip", "./content/sky"],
    ["content-music.zip", "./content/music"],
    ["content-particles.zip", "./content/particles"],
    ["2018client.zip", "./Client2018"],
    ["2020client.zip", "./Client2020"],
];
